### ISSUE TITLE
Typo in code/processing-scripts/01_grid_creation.R

### ISSUE THREAD

**Issue by fBedecarrats** [openkfw/mapme.protectedareas#106]
Bongiorno tutti,
A closing parenthesis appears to be missing in [code/processing-scripts/01_grid_creation.R](https://github.com/openkfw/mapme.protectedareas/blob/main/code/processing-scripts/01_grid_creation.R), on line 40. The closing parenthesis on line 42 should be removed.
Instead of:
```r
  st_write(hexa,
           paste(
             "../../datalake/mapme.protectedareas/processing/fishnet/honeycomb_",
             i,
             "_sqkm.gpkg",
             sep = "",
             append= FALSE # overwrite layer if exists. Use with caution
           )
  )
```
The code should be:
```r
  st_write(hexa,
           paste(
             "../../datalake/mapme.protectedareas/processing/fishnet/honeycomb_",
             i,
             "_sqkm.gpkg",
             sep = ""), # add closing parenthesis here
             append= FALSE # overwrite layer if exists. Use with caution
        # ) remove closing parenthesis here
  )
```
Otherwise "FALSE" gets pasted inside the file name and the argument `append = FALSE` is not passed to the `st_write` function.
Arriverderci,
FB

**Comment by Jo-Schie** [comment]
thanks for pointing that out @fBedecarrats . I just fixed it.
