### ISSUE TITLE
Progress track - dataset processing

### ISSUE THREAD

**Issue by Ohm-Np** [openkfw/mapme.protectedareas#41]
Issue dedicated to keep track of processing of the variables and to discuss any issues related to particular variables.

**All Protected Areas**

- [x] DOPA
- [x] Carbon balance
- [x] TEOW
- [ ] Mangrove gain and loss
- [x] WorldPop Population Count
- [ ] Global forest watch
- [x] Copernicus global land cover
- [ ] Terrain Ruggedness Index (TRI)
- [ ] Accessibility to Cities
- [x] Clay content

**Supported Protected Areas**

- [x] DOPA
- [x] Carbon balance
- [x] TEOW
- [x] Mangrove gain and loss
- [x] WorldPop Population Count
- [x] Global forest watch
- [x] Copernicus global land cover
- [x] Terrain Ruggedness Index (TRI)
- [x] Accessibility to Cities
- [ ] Clay content

**Comment by Jo-Schie** [comment]
Hi @Ohm-Np . Could i ask you to also process Fishing hours and clay content. They are marked "blue" in our table where all datasets are listed.

**Comment by Ohm-Np** [comment]
> Could i ask you to also process Fishing hours and clay content.

Yes sure, I will check on it.

**Comment by Ohm-Np** [comment]
Hi @Jo-Schie, for the datasets `clay content`, there are two categories available for download at 250m spatial resolution:

1. mean value/median value
2. standard depths (0, 10, 30, 60, 100 and 200 cm)

Which one would you suggest me to process at first?

**Comment by Jo-Schie** [comment]
Hi Om. 0,10 and 30 would be great!
