### ISSUE TITLE
Check links in Markdownfiles for data-processing

### ISSUE THREAD

**Issue by Jo-Schie** [openkfw/mapme.protectedareas#54]
I saw that the links in the section that describes the datasets (metadata links and download links) are not working in the rendered website. Could you please check on them? I guess it is only a formatting thing because they are actually translated in my browser e.g. like this 

_https://openkfw.github.io/mapme.protectedareas/"22https://data.unep-wcmc.org/pdfs/45/GMW_001_Metadata.pdf?1560444488%22"_

**Comment by Ohm-Np** [comment]
This is so weird. The links inside the paragraph works fine as in the first paragraph, if you click [web-based information system or IUCN/WDPA](https://openkfw.github.io/mapme.protectedareas/dopa-rest.html) . 
But the one which contains a bullet ahead of it or starts with new sentence doesn't work even if the URL is correct.

**Comment by Ohm-Np** [comment]
Ah okay where was I wrong.

**Comment by Ohm-Np** [comment]
Okay, I got the bug.
I have been using URL link inside the inverted commas.

**Comment by Ohm-Np** [comment]
Done!
