### ISSUE TITLE
Link to the source codes in the markdownfiles. 

### ISSUE THREAD

**Issue by Jo-Schie** [openkfw/mapme.protectedareas#55]
Some of the markdownfiles are using source-code from the repository like [this one:](https://openkfw.github.io/mapme.protectedareas/gmw-mangrove.html). 

```R
source("code/area_proj.R")
```

Since we cannot assume that all of the people who read and use the turials have also downloaded the github repo (probably only the minority does), people would need to be able to find the code in order to use it. You may want therefore to write something like:

_ We will now use a function from our repository. If you have downloaded our repository to your local machine, you can call the function as given below with the `source`command.  If you do not have a local copy, you can download the source-code for the function [here](https://github.com/openkfw/mapme.protectedareas/tree/main/code)._

**Assignment**: Please check on that in all markdownfiles that describe the routines, and copy and paste the last sentence wherever you source external code. And keep that in mind for the future ;)

**Comment by Ohm-Np** [comment]
Done!
