### ISSUE TITLE
Test code in mass processing

### ISSUE THREAD

**Issue by Jo-Schie** [openkfw/mapme.protectedareas#59]
Hi @Ohm-Np . I created a sample dataset that has about 11.600 AOIs. Could you please try to run a few data processing routines on a test-set of say 5000 AOIs:

- Terrain Ruggedness
- Accessibility
- Worldpop and
- Global Forest Watch

You might already try to implement parallel routines if you feel that serialized processing is too slow. Just keep in mind that we will have to process all 11.600 in the end. The Global Forest Watch functions already have the ability for parallel but the other three functions from you I guess do not have that yet built in. 

You can find the file in: "_../../datalake/mapme.protectedareas/output/polygon/sampling/sampling_AOIs_2021-09-15.gpkg"_

Please note that Global Forest Watch might have a problem. Darius said it is probably and authentication issue and not caused by the package. If you cannot make it work after a couple of days please visit this [issue](https://github.com/mapme-initiative/mapme.forest/issues/2) and also leave your feedback, so Darius may hopefully fix it.

**Comment by Ohm-Np** [comment]
Hi @Jo-Schie, the sampling strategy looks great however, due to lack of unique IDs of the polygons, it is somehow difficult to store the result as table only. It might create confusion.

The possible solution could be to keep the geometry table intact and save the result as geopackage but this might result in large-sized files. I will soon update here the benchmarks from the processing routine.

**Comment by Ohm-Np** [comment]
**Progress chart**

All **_11,600_** AOIs

- [ ] Terrain Ruggedness
- [ ] Accessibility
- [ ] Worldpop
- [ ] Global Forest Watch

Sample **_5,000_** AOIs

- [ ] Terrain Ruggedness
- [ ] Accessibility
- [ ] Worldpop
- [ ] Global Forest Watch

**Comment by Jo-Schie** [comment]
hi om. i checked and subversion was already installed in the VM. Have you opened an issue with Darius in the github or did you speak via email?
