### ISSUE TITLE
Process burnt areas and fire hotspot

### ISSUE THREAD

**Issue by Ohm-Np** [openkfw/mapme.protectedareas#63]
**Possible sources**

1.  300m resolution global burnt areas from [Copernicus](https://land.copernicus.eu/global/products/ba) 
      - Monthly composite, July 2020 - present  [Sentinel]
      - April 2014 - present [PROBA-V]

2. 500m resolution global burnt areas MODIS [USGS](https://lpdaac.usgs.gov/products/mcd64a1v006/)

3. [VIIRS](https://viirsfire.geog.umd.edu/maps) Active fire 

**_Progress overview_**

- [ ] supported PAs
- [ ] all PAs
- [ ] supported buffer polygons
- [ ] all buffer polygons
- [ ] sample points

**Comment by Jo-Schie** [comment]
the suggested routine seems reasonable for me. Please go ahead

**Comment by Jo-Schie** [comment]
check if results are accurate and close issue. Burned areas can be done at a different time.
