### ISSUE TITLE
Please check results from TEOW for circle polygons AOI

### ISSUE THREAD

**Issue by Jo-Schie** [openkfw/mapme.protectedareas#64]
Hi @Ohm-Np . I checked the results from the polygon processing. 

There are three issues for the TEOW data in `      "../../datalake/mapme.protectedareas/processing/sampling_results/teow_eco_biome_long.csv",`

1. There is one column called `biome_intersect_sqkm_` so it does not contain the actual name of the biome. 
2. zero values are coded as NA which is bad practice. NAs should only be NAs if there is missing data. If the area is equal zero the corresponding value should be zero
3. There are 4869 columns that do not contain any area from any of the `biomes`.  My first guess was, that this is because teow maybe only covers part of the area, but that is not the case. I plotted the missing values, and they are all over the original reasearch area. So I am not sure, where the problem lies. You can recreate my short consistency analysis with the code below if needed. 

```R
# ---- create matching db ----
# load again sampling ids
sampling.ids.original<-
  read_sf("../../Om/test/sampling_October-20-2021.gpkg")
# function to load matching data and transform to wide
f.load <- function(my_data_dir)
{
  pivot_wider(read.csv(my_data_dir),
              id_cols = "UID")
}

# apply on all relevant datasets which are structured in long
matching_data <-
  lapply(
    c(
      "../../datalake/mapme.protectedareas/processing/sampling_results/accessibility_5k_10k_long.csv",
      "../../datalake/mapme.protectedareas/processing/sampling_results/accessibility_50k_100k_long.csv",
      "../../datalake/mapme.protectedareas/processing/sampling_results/clay_content_0_10_30_long.csv",
      "../../datalake/mapme.protectedareas/processing/sampling_results/teow_eco_biome_long.csv",
      "../../datalake/mapme.protectedareas/processing/sampling_results/terrain_ruggedness_index_long.csv",
      "../../datalake/mapme.protectedareas/processing/sampling_results/worldpop_population_count_long.csv",
      "../../datalake/mapme.protectedareas/processing/sampling_results/gfw_area_loss_long.csv"
    ),
    f.load
  )
# left join all of the data
matching_data_combined <-
  matching_data %>%
  reduce(left_join, by = "UID")
# add treatment variable
matching_data_combined <-
  left_join(matching_data_combined,
            sampling.ids.original)

# remove irrelevant columns
matching_data_combined <-
  matching_data_combined %>%
  select(-c(
    geom,
    clay_content_0_cm,
    clay_content_10_cm,
    starts_with("teow_intersect"),
    # biome_intersect_sqkm_,
    terrain_ruggedness_index_median,
    terrain_ruggedness_index_standard_deviation
  ))

# rename columns
colnames(matching_data_combined)
matching_data_combined<-
  matching_data_combined%>%
  rename(travel_time_to_nearby_cities_min_5k_10k=travel_time_to_nearby_cities_min.x,
         travel_time_to_nearby_cities_min_50k_100k=travel_time_to_nearby_cities_min.y)

## replace NAs in biomes data with zero ()
# first check whether there are any true NAs (e.g. because there is not data e.g. because the AOIs are not covered by TEOW)
test <-
  matching_data_combined %>%
  select(starts_with("biome")) %>%
  rowSums(., na.rm = T)
# 

length(sampling.ids.original[which(test==0),"strata"])
plot(sampling.ids.original[which(test!=0),"strata"])
# there is clearly now geographical pattern regarding those values that are zero. Hence it must be most probably some programming issue. 

# check if a lot of those values come from the supported PAs strata
table(st_drop_geometry(sampling.ids.original[which(test!=0),"strata"]))

```

**Comment by Ohm-Np** [comment]
> There is one column called biome_intersect_sqkm_ so it does not contain the actual name of the biome.

I checked the TEOW gpkg. There should be 14 total biomes (from biome number 1 to 14) but I found there were two extra biome number created (98 & 99) which corresponds to the **NA** values in the column `BIOME_NAME`. So, the error might relate to this. I will cross-check this with origial geopackage which comes without biome information.

> zero values are coded as NA

I think NA values were created after converting them to wider format. As per the script logic, it only stores the value of the biomes where intersection occured and it doesn't assign anything to other columns. Now, I will try to save the results both in wide and long format and see if this happens or not. 

> There are 4869 columns that do not contain any area from any of the biomes

I am now trying to process for the missing samples and wil update you soon.

**Comment by Ohm-Np** [comment]
**UPDATE**

Now, I know where the error came from (about missing data). 

While doing parallelization, if some of the cores encounter error, then it stops pocessing for every routines channelled through that particular core. I am quite not sure yet how to overcome this or may be by using less cores 🤔

**Comment by Ohm-Np** [comment]
Hi @Jo-Schie , 

Please use the new CSV which contains the value of missing sample polygons (for biome)

_datalake/mapme.protectedareas/processing/sampling_results/teow_biome_long_final.csv_

**Comment by Jo-Schie** [comment]
Thanks I'll try!
