### ISSUE TITLE
Process climatic variables

### ISSUE THREAD

**Issue by Ohm-Np** [openkfw/mapme.protectedareas#67]
The datasets are available in two different spatial and temporal resolution combinations for precipitation and temperature:
|Data|Temporal coverage|Temporal resolution|Spatial resolution|Remarks|
|-----|----------------------|-------------------|----------|---|
|Precipitation|1970-2000|aggregated over years|~1 sqkm|Monthly aggregate: total 12 rasters for 12 different months|
|Precipitation|2000-2009 & 2010-2018|Annual|~21 sqkm|12 rasters per year|
|Average temperature|1970-2000|aggregated over years|~1 sqkm|Monthly aggregate: total 12 rasters for 12 different months|
|Min. Temperature & Max. Temperature|2000-2009 & 2010-2018|Annual|~21 sqkm|12 rasters per year|

What do you think @Jo-Schie, which raster datasets should we process first?

**Comment by Jo-Schie** [comment]
Hi Om. Please go for the 1 sqkm res first. What is the temporal resolution? Annually? Or can we get this also on a monthly base?

**Comment by Ohm-Np** [comment]
We can get 1 sqkm rasters only on monthly base. They are aggregated over years e.g., one raster for (jan 1970, jan 1971,.... jan 2000) and so on for other months, thus total 12 rasters available for the period.

**Comment by Jo-Schie** [comment]
That's perfect

**Comment by Jo-Schie** [comment]
please check result for accuracy and then issue if all looks good.

**Comment by Ohm-Np** [comment]
Hi @Jo-Schie, 

Please find the results for mean temperature (2000-2018) here:-
`"../../datalake/mapme.protectedareas/output/polygon/temperature/2000-2018/"`

and mean precipitation (2000-2018) here:-
`../../datalake/mapme.protectedareas/output/polygon/precipitation/2000-2018/"`
