### ISSUE TITLE
Process Accessibility and GFW for new AOIs

### ISSUE THREAD

**Issue by Jo-Schie** [openkfw/mapme.protectedareas#68]
Hi Om,

I am updating our AOIs for the Impact Evaluation analysis. Could you please process these two datasets for me ASAP:

```R
aois_supported<-read_sf("../../datalake/mapme.protectedareas/output/polygon/sampling/fishnets/fishnet_within_10km.gpkg")

aois_aux<-read_sf("../../datalake/mapme.protectedareas/output/polygon/sampling/fishnets/fishnet_within_countries_100km.gpkg")

```
For the first dataset (aois supported) I need all the variables as last time with the AOIs. 
For the second (aois_aux) I only need GFW and Accessibilty. This data will be only used in an intermediary step. I would like you to ask to process this dataset **first**, because I need it quickly to then sample non-supported areas.

**Comment by Ohm-Np** [comment]
Hi @Jo-Schie, I got following error while loding `aois_aux` & other polygons in this directory to R:

```
Error: Cannot open "/datadrive/datalake/mapme.protectedareas/output/polygon/sampling/fishnets/fishnet_within_countries_100km.gpkg"; The source could be corrupt or not supported. See `st_drivers()` for a list of supported formats.
In addition: 
Warning message:
attempt to write a readonly database: this file is a WAL-enabled database. It cannot be opened because it is presumably read-only or in a read-only directory. (GDAL error 1) 
```

**Comment by Jo-Schie** [comment]
Hi Om. I just changed permissions. Can you check?

**Comment by Ohm-Np** [comment]
It's working now. Thanks!

**Comment by Ohm-Np** [comment]
I have finished processing GFW data for buffer polygons

`"../../datalake/mapme.protectedareas/output/buffer_polygons/GFW/"`

**Comment by Jo-Schie** [comment]
Hi @Ohm-Np .
I checked `"../../datalake/mapme.protectedareas/output/polygon/sampling/fishnets/fishnet_within_countries_100km_GFW.csv"` and it seems that only from 2013 the `area` estimates are valid:

![image](https://user-images.githubusercontent.com/25028884/143229025-59376a18-812c-4892-b620-9699c481864b.png)


could you please check?

**Comment by Ohm-Np** [comment]
>  it seems that only from 2013 the area estimates are valid

I checked the raw csv files, it is fine there but when we load it in R, the area column is somehow getting the values from geometry columns.

**Comment by Jo-Schie** [comment]
did you maybe safe an sf object as csv? MAybe you need to transform it first with `st_drop_geometry` or something similiar?

**Comment by Ohm-Np** [comment]
I have fixed it now

**Comment by Ohm-Np** [comment]
> did you maybe safe an sf object as csv? MAybe you need to transform it first with `st_drop_geometry` or something similiar?

Yes, I think that was the problem

**Comment by Jo-Schie** [comment]
Thanks. Can you tell me how fast or slow processing time is for the small polygons in 
`aois_supported<-read_sf("../../datalake/mapme.protectedareas/output/polygon/sampling/fishnets/fishnet_within_10km.gpkg")`. This will determine how big of a sample we can process for the control areas outside. Maybe we can also scale up the machine for just that task.

**Comment by Ohm-Np** [comment]
Considering `GFW` processing for `aoi_aux` polygons (2086 polygons), it took ~14 hours using **6 cores**.

For `accessibility`, it was just few minutes. 

I guess we can complete processing these small polygons (6500 polygons) over weekend or so. I am now on it.

**Comment by Jo-Schie** [comment]
just wait a little bit more with the 6500. I will increase the machine after I take the sample. Can you tell me about the accessibilty variables? Did you take the mean accessibility value for the 2086 polygons?

**Comment by Ohm-Np** [comment]
> Did you take the mean accessibility value for the 2086 polygons?

No, I took `min` for accessibility

**Comment by Jo-Schie** [comment]
Could you take mean please

**Comment by Ohm-Np** [comment]
Done!

**Comment by Ohm-Np** [comment]
Please find the latest results of `accessibility` here:

`"../../datalake/mapme.protectedareas/output/polygon/accessibility_to_cities/"`

`1. supportedPAs`
The routine could not process **10** polygons. I checked each polygon and found one similarity i.e. small area (<1 sqkm in many cases). There are very few cells within those polygons, thus values are either same throughout polygons or have very low min/max range. Due to this, there was error while **rasterizing** the polygons. 

`2. allPAs`
The routine could not process **1602** polygons with the similar reason as above.

I am still trying to find a way to rasterize ignoring those small cell values.

**Comment by Jo-Schie** [comment]
Hi @Ohm-Np. Never mind solving this now. But We should check which data is causing the issue and exclude it from the analysis. Maybe have a look in QGIS. I remember that there are some without actual geometry information and some that are just not really PAs. Please filter out both types before with this 

'"DESIG_ENG" != 'UNESCO-MAB Biosphere Reserve' AND "GEOMETRY_TYPE" != 'POINT''

And see if it solves some problems. For the others you could have a quick look in QGIS and report back what they are. Otherwise let's focus now on the GFW data and the package. This is currently much more important to me.
