### ISSUE TITLE
Irrecoverable CArbon dataset

### ISSUE THREAD

**Issue by Jo-Schie** [openkfw/mapme.protectedareas#69]
Hi @Ohm-Np : Could you check how difficult it is to process this dataset:

[https://www.nature.com/articles/s41893-021-00803-6](https://www.nature.com/articles/s41893-021-00803-6)

and report back here. Someone from the team would like to have this information.

**Comment by Ohm-Np** [comment]
The processing seems quite simple. The global raster size is ~2 GB for `irrecoverable carbon`. There are three raster layers in the zip file of irrecoverable carbon (i.e. soil, biomass & total). The layer `total` is I guess they would like to have a look on. 

The other two carbon datastets available are:
`manageable carbon` and `vulnerable carbon`

**Comment by Jo-Schie** [comment]
Cool. Could you process the irrecoverable total please for supported PAs?

**Comment by Ohm-Np** [comment]
Please find the results here:

`"../../datalake/mapme.protectedareas/output/polygon/irrecoverable_carbon/irrecoverable_carbon_2018_supportedPAs.csv"`

**Comment by Jo-Schie** [comment]
please compare results with original data to check for consistency and if the data looks good you can close the issue.
