### ISSUE TITLE
Modeling: Missing BMZ numbers for projects

### ISSUE THREAD

**Issue by melvinhlwong** [openkfw/mapme.protectedareas#70]
The project database has a lot of projects without a BMZ number.
projectdata_database<-
  read_csv("../../datalake/mapme.protectedareas/output/matching/model_frames/projectdata_supported.csv")

This happens particularly for 2008. @Jo-Schie Do you know what happened here? We are losing a lot of data here, because there I won't be able to attribute the disbursements to the polygons.

**Comment by Jo-Schie** [comment]
Not sure why that is the case... but I can look into it. Nevertheless we are reprocessing the whole database so I would prefer to wait for the results (end of this week) and then see if the problem persists...

**Comment by melvinhlwong** [comment]
check out the file 00_clean_data.R. I finally managed to create the data structure. Once we have the new data, we can run the code and be ready (I hope) for the analysis.

@Jo-Schie can you check if you have missing BMZ Numbers in your new "projectdata_supported.csv"?

**Comment by melvinhlwong** [comment]
@yotaae Yota, not sure. But did we solve this issue already?

**Comment by Jo-Schie** [comment]
This issue was solved by changing the read function
