### ISSUE TITLE
problem with treamtent cells being used as control

### ISSUE THREAD

**Issue by Jo-Schie** [openkfw/mapme.protectedareas#74]
Hi @melvinhlwong 👍 
I just plotted treatment cells for 2007 and 2015 together and it seems like we have cells that are both, treatment and control. I would have guessed, that this should not happen but currently it does. Not sure what might be the problem but I am attaching a map so that you can see it. 

![grafik](https://user-images.githubusercontent.com/25028884/147148375-f5ce2d87-6dc7-4e9b-82d4-673bff258c12.png)

**Comment by Jo-Schie** [comment]
@melvinhlwong : We are both assigned to resolve this issue. I am not sure what we agreed upon who would look into it.

**Comment by melvinhlwong** [comment]
I think I wanted to check on this. It's ready for review by me. So we should not discuss this with Jochen today

**Comment by melvinhlwong** [comment]
this problem is now solved. We did perform the matching on PA level with datasets by country. Each country dataset groups the PA cells as group=1. Now, no treatment cell can enter as control cell anymore
