### ISSUE TITLE
Treated polygons without corresponding WDPA-ID or BMZ-Nr in matched panels

### ISSUE THREAD

**Issue by yotaae** [openkfw/mapme.protectedareas#75]
I have noticed that our matched panels contain 259 treated polygons (treat_ever == 1) without a corresponding WDPA-ID or a BMZ-No. Treated polygons with disbursements should at least have a corresponding BMZ-No. 

An example: In the matched panel for year 2006, the polygon with poly_id "id_1301" is assigned treat_ever==1, disbursements start in year 2006. However, there is no corresponding BMZ-No or WDPA-ID. 

I came across this issue when trying to merge the matched panels with project data and wdpa variables. We should look into this in one of our sessions @Jo-Schie @melvinhlwong

**Comment by Jo-Schie** [comment]
can you check whether there is another column that is only called "id" and whether you can find these values inside: 

![image](https://user-images.githubusercontent.com/25028884/149351690-ae3a41c8-4296-4c65-9b54-5d4791affdd9.png)

**Comment by yotaae** [comment]
@Jo-Schie: I have just checked this and there is a column called "id" but I can't find the above values. In fact, all the polygons which are missing BMZ-No and WDPA-ID have missing values in the "id" column.

**Comment by Jo-Schie** [comment]
I thin we need @melvinhlwong to look into this since he created the treat ever variable...

**Comment by Jo-Schie** [comment]
I thin we can close this issue which was fixed by importing differently the cabs that had interpreted wrongly the column type of the ids
