### ISSUE TITLE
GRACE-based drought indicator datasets

### ISSUE THREAD

**Issue by Ohm-Np** [openkfw/mapme.protectedareas#77]
**Dataset:**

GRACE-based shallow groundwater drought indicator  
|Spatial Coverage|Global|
|------------------|--------|
|Spatial Resolution|0.25 degrees|
|Temporal Coverage|2003-Feb to Present|
|Temporal Resolution|Weekly updates|
|Unit|percentile|
|Inference| `percentile` describes current wet or dry conditions showing the probability of occurrence - with lower values meaning dryer than normal, and higher values meaning wetter than normal|

I already created function (API connecting to nasagrace) to download these rasters. 
Of which time period you need the data @Jo-Schie? Should I download all or may be yearly by choosing specific dates of the year?

`Note: Size of one raster file is ~900 kb`

**Comment by Jo-Schie** [comment]
Hi Om. Great. We will need all data for all years. I will have to come up with a concept still on how to aggregate the values afterwards but for the moment I would suggest you just create mean values for all weeks. Please also store at least some of the input data. I would like to look at it afterwards.

**Comment by Ohm-Np** [comment]
Please find the result (for supportedPAs) here:

**Comment by Ohm-Np** [comment]
Please find the result (for supportedPAs) here:
`"../../datalake/mapme.protectedareas/output/polygon/drought_indicator/gws_supportedPAs.csv"`

and the rasters here:
`"../../datalake/mapme.protectedareas/input/drought_indicator/"`

I have created a new column called `date` to read the data easily, sample data:-

```ruby
WDPA_PID       date                  name         value
6675       2003-02-03     mean_percentile      86.57270
478068     2003-02-03     mean_percentile      43.94059
478085     2003-02-03     mean_percentile      96.69246
478089     2003-02-03     mean_percentile      63.06751
478101     2003-02-03     mean_percentile      51.89230
478130     2003-02-03     mean_percentile      69.02441
```
