### ISSUE TITLE
Create additional covariates for regression

### ISSUE THREAD

**Issue by Jo-Schie** [openkfw/mapme.protectedareas#89]
- [x] precipitation anomalies -> drought risk /wildfire risk/fire deforestation suitability 
- [x] shallow groundwater anomalies -> drought risk /wildfire risk/fire deforestation suitability 
- [x] hurricanes (currently not in package, needs manual processing)
- [ ] disbursement data (e.g. disbursement per ha)

**Comment by Jo-Schie** [comment]
@melvinhlwong : Bitte code schicken für disbursement

**Comment by melvinhlwong** [comment]
https://github.com/openkfw/mapme.protectedareas/blob/22c2a7bf0dc63cf6a9649f3ff94eb958465ebe3c/code/development/00_clean_data.R#L123

Hi @Jo-Schie anbei findest du den LInk zur code sektion. Die geht von Zeile 123-131 und wir hatten das sogar zusammen gemacht. Ich hoffe das hilft

**Comment by Jo-Schie** [comment]
Todo:

Create table: wdpa_id + bmz + area wdpa

```R
group_by(bmz) %>%
summarize (sum(area_reported))

# divide by financial disbursement data

```

-> link financial disbursement to gridcells via WDPA id

**Comment by Jo-Schie** [comment]
i will close this issue because disbursement data will need a separate issue.
