### ISSUE TITLE
Clustering of standard errors 

### ISSUE THREAD

**Issue by Jo-Schie** [openkfw/mapme.protectedareas#99]
- [ ] Create crosstables for year of protected area assignment in our treated portfolio (should be inside the WDPA data) @yotaae 
- [ ] check relevant literature (PA vs. non-PA, panel, matching studies)
- [ ] decide on one or several clustering routines (see below). 

Suggested solutions so far:

- Cluster on admin areas alone (e.g. country or states) -> problematic since PAs is missing
- cluster on PA areas alone -> problematic because of huge non-protected group
- combined approach e.g. "Acre-Area A", "Acre-Area B", ..., "Acre-Nonprotected" (where Acre is an example for admin area on the levels of states (Brazil)
- Cluster based on remoteness (e.g. distance to protected areas). -> not sure because this is part of the matching already...

**Comment by melvinhlwong** [comment]
@Jo-Schie Mir ist eingefallen warum clustering auf country Ebene nicht geht. Aus irgendeinem Grund errechnet mir R keine Standard Fehler aus. Das wundert mich, da ich schon mal für ein anderes Papier bereits in einem ähnlichen setting auf country Ebene geclustered habe.

Es bleibt also nichts übrig als vorläufig auf PA Ebene zu cllustern und die Controll Groups als einen Cluster zu nehmen pro Land.

**Comment by Jo-Schie** [comment]
Ich frag nochmal bei den Uni Bonn Leuten nach. Ggf hatten die mal ein ähnliches Issue ...

**Comment by melvinhlwong** [comment]
Das wäre sehr gut. kannst du mich in CC setzen?
